In [1]:
import pandas as pd
import os

Could not install Mage, made transformations locally

In [50]:
green_trip_files = []
for file in os.listdir('.'):
    if file.endswith('.csv.gz'):
        green_trip_files.append(pd.read_csv(file,low_memory=False,parse_dates=['lpep_pickup_datetime','lpep_dropoff_datetime']))

In [51]:
#Q1
green_trip_df = pd.concat(green_trip_files)
green_trip_df.shape

(266855, 20)

In [52]:
#Q2
#if I made it compare using != 0 instead it would result in 257400 rows but it would keep the NaNs in the data
green_trip_filtered = green_trip_df[(green_trip_df['passenger_count']>0) & (green_trip_df['trip_distance']>0)]
green_trip_filtered.shape

(139370, 20)

In [53]:
#Q5
[col_name for col_name in green_trip_filtered.columns if 'ID' in col_name]

['VendorID', 'RatecodeID', 'PULocationID', 'DOLocationID']

In [54]:
green_trip_filtered = green_trip_filtered.rename(columns = {
    'VendorID':'vendor_id'
    ,'RatecodeID':'ratecode_id'
    ,'PULocationID':'pu_location_id'
    ,'DOLocationID':'do_location_id'
} )
green_trip_filtered.columns

Index(['vendor_id', 'lpep_pickup_datetime', 'lpep_dropoff_datetime',
       'store_and_fwd_flag', 'ratecode_id', 'pu_location_id', 'do_location_id',
       'passenger_count', 'trip_distance', 'fare_amount', 'extra', 'mta_tax',
       'tip_amount', 'tolls_amount', 'ehail_fee', 'improvement_surcharge',
       'total_amount', 'payment_type', 'trip_type', 'congestion_surcharge'],
      dtype='object')

In [55]:
#Q3
green_trip_filtered['lpep_pickup_date']=green_trip_filtered['lpep_pickup_datetime'].dt.date
green_trip_filtered

,vendor_id,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,ratecode_id,pu_location_id,do_location_id,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,lpep_pickup_date
0,2.0,2020-10-01 00:31:19,2020-10-01 00:34:55,N,1.0,7,7,1.0,0.79,5.0,...,0.5,1.58,0.0,NaN,0.3,7.88,1.0,1.0,0.0,2020-10-01
1,2.0,2020-10-01 00:42:12,2020-10-01 00:43:51,N,1.0,179,7,1.0,0.50,4.0,...,0.5,0.00,0.0,NaN,0.3,5.30,2.0,1.0,0.0,2020-10-01
2,2.0,2020-10-01 00:53:09,2020-10-01 00:55:39,N,1.0,179,223,1.0,0.60,4.0,...,0.5,1.06,0.0,NaN,0.3,6.36,1.0,1.0,0.0,2020-10-01
3,1.0,2020-10-01 00:12:29,2020-10-01 00:20:08,N,1.0,134,216,2.0,4.40,13.5,...,0.5,0.00,0.0,NaN,0.3,14.80,2.0,1.0,0.0,2020-10-01
4,1.0,2020-10-01 00:32:38,2020-10-01 00:43:02,N,1.0,82,7,1.0,2.90,10.5,...,0.5,0.00,0.0,NaN,0.3,11.80,2.0,1.0,0.0,2020-10-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46287,2.0,2020-12-31 23:08:35,2020-12-31 23:13:00,N,1.0,41,74,1.0,0.79,5.0,...,0.5,0.00,0.0,NaN,0.3,6.30,2.0,1.0,0.0,2020-12-31
46288,2.0,2020-12-31 23:11:04,2020-12-31 23:20:08,N,5.0,41,116,2.0,2.31,12.0,...,0.0,0.00,0.0,NaN,0.3,12.30,2.0,2.0,0.0,2020-12-31
46289,2.0,2020-12-31 23:24:33,2020-12-31 23:40:24,N,5.0,116,119,1.0,5.73,20.0,...,0.0,0.00,0.0,NaN,0.3,20.30,2.0,2.0,0.0,2020-12-31
46290,2.0,2020-12-31 23:13:59,2020-12-31 23:16:20,N,1.0,42,42,1.0,0.31,3.5,...,0.5,0.00,0.0,NaN,0.3,4.80,2.0,1.0,0.0,2020-12-31
46291,2.0,2020-12-31 23:54:15,2021-01-01 00:11:17,N,1.0,75,167,1.0,3.74,15.0,...,0.5,1.00,0.0,NaN,0.3,17.30,1.0,1.0,0.0,2020-12-31

In [56]:
#Q4
green_trip_filtered['vendor_id'].unique()

array([2., 1.])

In [58]:
#Q6
green_trip_filtered['lpep_pickup_date'].unique().shape

(95,)